FiftyOne.Pipeline.Web.Shared/Services/ClientsidePropertyService.cs
Web Integration/Tests/FiftyOne.Pipeline.Web.Shared.Tests/ClientsidePropertyServiceTests.cs

Javascript and JSON responses will now include the Cross Origin Resource HTTP header Access-Control-Allow-Origin in the response when the Origin header is present in the request. This enables the Javascript and JSON end points to be used from origins other than the one hosting the service aiding the creation of services.

Add the Access-Control-Allow-Origin response header when Origin present in request.

---

ci/build-package.ps1

This has now been changed in the CI script, so the package will include DLLs for Framework.
Closes #27

BUG/BUILD: The FiftyOne.Pipeline.Web package needs to be built with MSBuild in order to support .NET Framework.

---

FiftyOne.Pipeline.Engines/Configuration/DataFileConfiguration.cs
FiftyOne.Pipeline.Engines/Configuration/DataFileConfigurationBuilderBase.cs
FiftyOne.Pipeline.Engines/Constants.cs
Tests/FiftyOne.Pipeline.Engines.FiftyOne.Tests/Configuration/FiftyOneDataFileConfigurationBuilderTests.cs
Tests/FiftyOne.Pipeline.Engines.FiftyOne.Tests/Data/UrlFormatterTests.cs

BUG/TEST: The default data file configuration builder reused a static list for license keys.
This means that when mutiple builders are used, they are all accessing the same static list. So license keys are shared across engines. This is not the correct behaviour, but will usually not be noticed as one engine is more common.
Also added a test to confirm this is fixed.
TEST: Added tests for update URL formatting. 
closes #45

BUG/TEST: The default data file configuration builder reused a static list for license keys.

---

FiftyOne.Pipeline.CloudRequestEngine/CloudRequestException.cs
FiftyOne.Pipeline.CloudRequestEngine/FlowElements/CloudAspectEngineBase.cs
FiftyOne.Pipeline.CloudRequestEngine/FlowElements/CloudRequestEngine.cs
FiftyOne.Pipeline.Core/Constants.cs
FiftyOne.Pipeline.Core/Exceptions/PropertiesNotYetLoadedException.cs
FiftyOne.Pipeline.Core/FlowElements/IFlowElement.cs
FiftyOne.Pipeline.Core/FlowElements/IPipeline.cs
FiftyOne.Pipeline.Core/FlowElements/ParallelElements.cs
FiftyOne.Pipeline.Core/FlowElements/Pipeline.cs
FiftyOne.Pipeline.Core/FlowElements/PipelineBuilderBase.cs
FiftyOne.Pipeline.Engines.TestHelpers/TestPipeline.cs
FiftyOne.Pipeline.Engines/FlowElements/AspectEngineBase.cs
FiftyOne.Pipeline.Engines/FlowElements/IAspectEngine.cs
FiftyOne.Pipeline.Engines/Services/MissingPropertyService.cs
FiftyOne.Pipeline.Web.Shared/PipelineWebIntegrationOptions.cs
Tests/FiftyOne.Pipeline.CloudRequestEngine.Tests/CloudAspectEngineBaseTests.cs
Tests/FiftyOne.Pipeline.CloudRequestEngine.Tests/CloudRequestEngineBuilderTests.cs
Tests/FiftyOne.Pipeline.CloudRequestEngine.Tests/CloudRequestEngineTests.cs
Tests/FiftyOne.Pipeline.Core.Tests/FlowElements/PipelineTest.cs
Tests/FiftyOne.Pipeline.Engines.Tests/Services/MissingPropertyServiceTests.cs
Web Integration/FiftyOne.Pipeline.Web.Framework/Providers/PipelineCapabilities.cs
Web Integration/FiftyOne.Pipeline.Web.Framework/WebPipeline.cs
Web Integration/Tests/FiftyOne.Pipeline.Web.Framework.Tests/FiftyOne.Pipeline.Web.Framework.Tests.csproj
Web Integration/Tests/FiftyOne.Pipeline.Web.Framework.Tests/WebPipelineEvidenceFillerTests.cs

See https://github.com/51Degrees/pipeline-dotnet/issues/44
- Call `GetCloudEvidenceKeys` / `GetCloudProperties` from respective `CloudRequestEngine`'s property getters, instead of early assignment (in constructor).
- Add new `HasLoadedProperties` property on `IAspectEngine` interface for `MissingPropertyService` not to re-invoke `CloudRequestEngine.GetCloudProperties` when no response is available yet.
- Duplicate and deprecate `PipelineBuilderBase.SetSuppressProcessException` and `Constants.PIPELINE_BUILDER_DEFAULT_AUTO_SUPRESS_PROCESS_EXCEPTION` in favour of ones ending with an `s` --- to align with a spelling from [specification docs](https://github.com/51Degrees/specifications/blob/main/pipeline-specification/features/exception-handling.md?plain=1#L40).
- Make …

Lazify cloud request engine properties

---

Tests/FiftyOne.Pipeline.Engines.Tests/Services/DataUpdateServiceTests.cs
Web Integration/Tests/FiftyOne.Pipeline.Web.Framework.Tests/FiftyOne.Pipeline.Web.Framework.Tests.csproj
Web Integration/Tests/FiftyOne.Pipeline.Web.Framework.Tests/app.config

Assembly not found during both [CI action](https://github.com/51Degrees/pipeline-dotnet/runs/16737849869) and locally (VS 2022 on Windows 11) :
- Redirect `System.Runtime.CompilerServices.Unsafe` assembly reference to `6.0.0.0` in `app.config`
- Add local file cleanup _before_ running the logic (in addition to _after_) in a couple of test cases.
Test passes locally (VS 2022 on Windows 11) :

Fix missing runtime assembly for `FiftyOne.Pipeline.Web.Framework.Tests.Dependencies`

---

Tests/FiftyOne.Pipeline.Engines.Tests/Services/DataUpdateServiceTests.cs

Issue: https://github.com/51Degrees/pipeline-dotnet/issues/55
- Use `Times.AtLeastOnce` check as a strong assertion.
- Make `Times.Once` check less conclusive one.

`DataUpdateService_UpdateFromWatcher` test

---

Tests/FiftyOne.Pipeline.Engines.Tests/Services/DataUpdateServiceTests.cs

- https://github.com/51Degrees/pipeline-dotnet/actions/runs/6256335015/job/16987011987#step:5:385
- Add `sleep` before checking logger's contents.
- Dump logs from `_logger` into test output during `Cleanup`

Failed DataUpdateService_UpdateFromUrl_HttpException

---

ci/run-performance-tests.ps1

see https://github.com/actions/runner-images/issues/8598

Apply `cmake` downgrade workaround.

---

Web Integration/FiftyOne.Pipeline.Web.Framework/Providers/PipelineCapabilities.cs

- Check `FlowData.Errors` before attempting to get its values.
- Avoid throwing `PropertyMissingException` when `FlowData` contains suppressed errors.

Improve the safety of `PipelineCapabilities`

---

.github/workflows/monthly-copyright-update.yml
.github/workflows/nightly-documentation-update.yml
.github/workflows/nightly-package-update.yml
.github/workflows/nightly-prs-to-main.yml
.github/workflows/nightly-publish-main.yml
.github/workflows/nightly-submodule-update.yml
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElement/FlowElement/JavaScriptBuilderElement.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTests.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JsonBuilderElement/FlowElement/JsonBuilderElement.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JsonBuilderElementTests/JsonBuilderElementTests.cs
FiftyOne.Pipeline.Web.Shared/Services/ClientsidePropertyService.cs
Web Integration/Tests/FiftyOne.Pipeline.Web.Shared.Tests/ClientsidePropertyServiceTests.cs

- Convert constructor-initialized field into lazy `HeadersAffectingJavaScript` property (ClientsidePropertyService).
- Add `org-name` to workflow files.
- Wrap multiple calls in try-catch to ensure stable returns of certain paths.
- Add mocking of additional (now-checked by main code) properties in Unit Tests.
- Add `GetFallbackResponse` methods to `JavaScriptBuilderElement` and `JsonBuilderElement` with respective Unit Tests.
- Use new methods when `data` is unprocessed or contains errors.
- https://github.com/51Degrees/pipeline-dotnet/issues/75

Lazify clientside property service headers

---

FiftyOne.Pipeline.Engines.TestHelpers/FiftyOne.Pipeline.Engines.TestHelpers.csproj
FiftyOne.Pipeline.Examples.Shared/FiftyOne.Pipeline.Examples.Shared.csproj
Web Integration/FiftyOne.Pipeline.Web/FiftyOne.Pipeline.Web.csproj

- Set `PackageProjectUrl` to `https://51degrees.com`.
- https://github.com/51Degrees/device-detection-dotnet/issues/169

Add Project URL into Nuget package

---

FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElement/FlowElement/JavaScriptBuilderElement.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JsonBuilderElement/FlowElement/JsonBuilderElement.cs

- Add overloads with old protected signatures.
- Mark `JavaScriptBuilderElement.GetOrAddToData`, `JavaScriptBuilderElement.GetJSONFromData` and `IJsonBuilderElement.BuildJson` methods as `protected` and add doc-comments.
- https://github.com/51Degrees/pipeline-dotnet/pull/76

Add overloads with old protected signatures.

---

Examples/CustomFlowElement/Examples.CustomFlowElement.Data/Constants.cs
Examples/CustomFlowElement/Examples.CustomFlowElement.Data/StarSign.cs

- Move parsing out of `StarSign`.
- Use exact format instead of active locale.
- Make example work regardless of local settings ---- `DateTime.Parse` uses the conventions of the current culture --- [[ref^](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=net-8.0#system-datetime-parse(system-string))]

Move parsing out of `StarSign`. Use exact format.

---

FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/FiftyOne.Pipeline.JavaScriptBuilderElementTests.csproj
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTemplateTests.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTests.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTestsBase.cs
FiftyOne.Pipeline.Engines.TestHelpers/TestHttpServer.cs

- Move `FiftyOne.Pipeline.JavaScriptBuilderElementTests.csproj` to .NET 8.0 (enable Minimal API usage).
- Add `Access-Control-Allow-Origin: *` header to `TestHttpServer`'s responses.
- Split up `JavaScriptBuilderElementTests` class to introduce parent `JavaScriptBuilderElementTestsBase`.
- Add new test class `JavaScriptBuilderElementTemplateTests`.
- 🛠️ Build new JSON with JavaScript snippet property.
- 🛠️ Visit the page.
- 🗒️ Script invokes the snippet code.
- ❔ Observe POST data when script calls `json` endpoint. Check the data set by snippet is present.
- ❔ Check for `complete` callback by the script.
- ❔ Check the snippet was called by testing a flag in `window`.
- 🛠️ Replace a JSON with another JavaScript snippet property.
- 🛠️ Add new cookie.
- 🛠️ Reload the page.
- 🗒️ Script …

Mustache template behaviour tests

---

FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/CookiesTests.cs

This change set allows the tests introduced in https://github.com/51Degrees/pipeline-dotnet/pull/99 to pass after the merge of https://github.com/51Degrees/javascript-templates/pull/5 .

TEST: Offset expected `document.cookie` occurrences by 1.

---

FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElement/Constants.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElement/FlowElement/JavaScriptBuilderElement.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/CookiesTests.cs

Adding the query parameter `fod-js-enable-cookies` will override the option supplied to the element at construction.
This PR addresses #98 . However, the templates submodule will need to be update before the tests in this PR will pass.

FEAT: The enable cookies option for `JavaScriptBuilderElement` is now configurable per-request.

---

Examples/CustomFlowElement/3. Client-side evidence/ClientSideEvidence.Shared/FlowElements/SimpleClientSideElement.cs

- Replace `DateTime.Parse` calls with `DateTime.ParseExact`.
- The Example throws at different system locale settings:
```
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
An exception of type 'System.FormatException' occurred in System.Private.CoreLib.dll but was not handled in user code
String '21/03' was not recognized as a valid DateTime.
```

Use exact format for parsing `StarSign`.

---

FiftyOne.Pipeline.Core/FlowElements/PipelineBuilder.cs
Tests/FiftyOne.Pipeline.Core.Tests/FlowElements/PipelineBuilderTests.cs
Tests/FiftyOne.Pipeline.Core.Tests/HelperClasses/CompositeConfig/CompositeConfigElement.cs
Tests/FiftyOne.Pipeline.Core.Tests/HelperClasses/CompositeConfig/CompositeConfigElementBuilder.cs
Tests/FiftyOne.Pipeline.Core.Tests/HelperClasses/CompositeConfig/CompositeConfigFragment.cs
Tests/FiftyOne.Pipeline.Core.Tests/HelperClasses/CompositeConfig/ICompositeConfigFragmentContainer.cs

- Modify `PipelineBuilder` to also search for suitable extension setter-methods (in the same assembly as builder type).
- Add example:
- `CompositeConfigElementBuilder` class with
- reusable options subsection (`CompositeConfigFragment`)
- that is "inlined" at code completion level by `CompositeConfigFragmentExtensions`
- and `ICompositeConfigFragmentContainer` "trait" (applied to `CompositeConfigElementBuilder`).
- Add 3 unit tests:
- (control) Check the `CompositeConfigElementBuilder` directly (no `PipelineBuilder` used).
- (control) Check `PipelineBuilder` finding `CompositeConfigElementBuilder` (no properties set yet).
- (actual) Check `PipelineBuilder` using the builder extension methods (supplied to `CompositeConfigElementBuilder` by `CompositeConfigFragmentExtensions` via …

Allow `PipelineBuilder` use extension methods.

---

FiftyOne.Pipeline.Engines/Data/AspectPropertyValue.cs

Instead of checking the `HasValue` flag, `Value` was compared to `null`. The getter for `Value` throws an exception is `HasValue` is false. So this is now checked instead.

BUG: `ToString` method in `AspectPropertyValue` does not prevent exception.

---

FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JsonBuilderElement/FlowElement/JsonBuilderElement.cs
FiftyOne.Pipeline.Web.Shared/Services/ClientsidePropertyService.cs
Web Integration/FiftyOne.Pipeline.Web.Framework/WebPipeline.cs

Allows for ArgumentNullException / ArgumentException / KeyNotFoundException as well.
See
- https://github.com/51Degrees/pipeline-dotnet/blob/main/FiftyOne.Pipeline.Core/Data/FlowData.cs#L497-L501
- https://github.com/51Degrees/pipeline-dotnet/blob/main/FiftyOne.Pipeline.Core/TypedMap/TypedKeyMap.cs#L126-L145

Replace `catch (PipelineException e)` with `catch (Exception e)`.

---

Examples/UsageSharing/Examples.UsageSharing.csproj
FiftyOne.Pipeline.Core/FiftyOne.Pipeline.Core.csproj
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTemplateTests.cs
Tests/FiftyOne.Pipeline.Engines.FiftyOne.Tests/FiftyOne.Pipeline.Engines.FiftyOne.Tests.csproj
Web Integration/Examples/ExampleFrameworkWebsite/AspNet Framework MVC Example.csproj
Web Integration/FiftyOne.Pipeline.Web.Framework/FiftyOne.Pipeline.Web.Framework.csproj
Web Integration/FiftyOne.Pipeline.Web/FiftyOne.Pipeline.Web.csproj
Web Integration/Tests/FiftyOne.Pipeline.Web.Framework.Tests/app.config
Web Integration/Tests/FiftyOne.Pipeline.Web.Tests/FiftyOne.Pipeline.Web.Tests.csproj

- Remove import that failed package updates
- `$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets`
- Update packages
- Add more binding redirects to `FiftyOne.Pipeline.Web.Framework.Tests`
- Increase timeout `JavaScriptBuilderTemplate_ValidateSetCookieBlockCall` _(cause Ubuntu runner failed twice in a row)_
- https://github.com/51Degrees/pipeline-dotnet/actions/runs/11965618613/job/33359937813#step:5:1035
- https://github.com/postindustria-tech/pipeline-dotnet/actions/workflows/nightly-prs-to-main.yml
> WARNING: error: The imported project "/usr/share/dotnet/sdk/8.0.404/Microsoft/VisualStudio/v17.0/WebApplications/Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "/usr/share/dotnet/sdk/8.0.404/Microsoft/VisualStudio/v17.0/We …

Fix updates of "AspNet Framework MVC Example"

---

FiftyOne.Pipeline.Core/FlowElements/FlowElementBase.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JsonBuilderElementTests/FiftyOne.Pipeline.JsonBuilderElementTests.csproj
FiftyOne.Pipeline.Engines/Services/DataUpdateService.cs
Tests/FiftyOne.Pipeline.Benchmarks/FiftyOne.Pipeline.Benchmarks.csproj
Tests/FiftyOne.Pipeline.CloudRequestEngine.Examples.Tests/FiftyOne.Pipeline.CloudRequestEngine.Examples.Tests.csproj
Tests/FiftyOne.Pipeline.CloudRequestEngine.Tests/FiftyOne.Pipeline.CloudRequestEngine.Tests.csproj
Tests/FiftyOne.Pipeline.Core.Tests/FiftyOne.Pipeline.Core.Tests.csproj
Tests/FiftyOne.Pipeline.Engines.FiftyOne.Tests/FiftyOne.Pipeline.Engines.FiftyOne.Tests.csproj
Tests/FiftyOne.Pipeline.Engines.FiftyOne.Tests/FlowElements/ShareUsageElementTests.cs
Tests/FiftyOne.Pipeline.Engines.Tests/FiftyOne.Pipeline.Engines.Tests.csproj
Tests/FiftyOne.Pipeline.Engines.Tests/Services/DataUpdateServiceTests.cs
Tests/FiftyOne.Pipeline.Examples.Tests/FiftyOne.Pipeline.Examples.Tests.csproj
Web Integration/Examples/NetCore/AspNetCore Example.csproj
Web Integration/Tests/FiftyOne.Pipeline.Web.Shared.Tests/FiftyOne.Pipeline.Web.Shared.Tests.csproj
Web Integration/Tests/FiftyOne.Pipeline.Web.Tests/FiftyOne.Pipeline.Web.Tests.csproj
ci/options.json

Changes:
* update test and example projects to target .NET 8.0
* address an instability in ShareUsageElementTests
* fix FileSystemWatcher in DataFileUpdateService.cs to track a copy over event on macos which otherwise was not triggered.  the essential changed lines in that file are:
```csharp
watcher.NotifyFilter = NotifyFilters.LastWrite | NotifyFilters.FileName;
watcher.Created += DataFileUpdated;
```
all others are whitespace and line endings due to auto-formatting in the IDE
* introduce NullLogger into FlowElementBase - otherwise it crashed in Finalize() because logger was unavailable

Enable build on macos-13 runners

---

FiftyOne.Pipeline.CloudRequestEngine/FlowElements/PropertyKeyedCloudEngineBase.cs
FiftyOne.Pipeline.Core/Data/DataBase.cs
FiftyOne.Pipeline.Core/Data/IData.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElement/FlowElement/JavaScriptBuilderElementBuilder.cs
FiftyOne.Pipeline.Engines.TestHelpers/MockFlowData.cs
FiftyOne.Pipeline.Engines/Services/DataUpdateService.cs
Tests/FiftyOne.Pipeline.Core.Tests/Data/ElementDataTests.cs
Tests/FiftyOne.Pipeline.Core.Tests/Data/EvidenceTests.cs
Tests/FiftyOne.Pipeline.Engines.FiftyOne.Tests/FlowElements/SetHeadersElementTests.cs

* addresses: #147 - `IData.PopulateFrom(IEnumerable)` was added the old `PopulateFromDictionary` method was marked as Obsolete
* also addresses #150 changed logger property visibility on JavaScriptBuilderElementBuilder

introduce IData.PopulateFrom(IEnumerable) + a property visibility change on JavaScriptBuilderElementBuilder

---

FiftyOne.Pipeline.CloudRequestEngine/FlowElements/CloudRequestEngine.cs

FIX: Properly Synchronize the SendAsync call using suggested method for netstandard. https://learn.microsoft.com/en-us/archive/blogs/jpsanders/asp-net-do-not-use-task-result-in-main-context

FIX: Properly Synchronize the SendAsync call

---

FiftyOne.Pipeline.Core/Data/FlowData.cs
FiftyOne.Pipeline.Core/FlowElements/Pipeline.cs
Tests/FiftyOne.Pipeline.Core.Tests/Data/FlowDataExtendedGetWhereTests.cs
Tests/FiftyOne.Pipeline.Core.Tests/Data/FlowDataTests.cs

Change FlowElements to return ALL flow elements, including sub elements. 
Before, sub elements that are part of a parallel element would not be returned as the Parallel element would not be unpacked and will not contain an element data key. 
Now, unpack the parallel elements to create the full list.
Add extended test methods for the GetWhere method to ensure that all element data for all elements (including parallel elements is returned). These have been added to a separate file/test class as the set up for these tests differs from the setup for the other FlowData tests.

Change FlowElements to return ALL flow elements, including sub elements

---

FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/FiftyOne.Pipeline.JavaScriptBuilderElementTests.csproj
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTestsBase.cs

as Chrome has updated to 132 on some gh runners and Webdriver package is not exactly ready for this - hence the explicit protocol version is temporarily set - can be upgraded later.

temporarily set devtools protocol version to 127 for selenium tests

---

FiftyOne.Pipeline.Core/FlowElements/PipelineBuilder.cs
Tests/FiftyOne.Pipeline.Core.Tests/FlowElements/PipelineBuilderTests.cs
Tests/FiftyOne.Pipeline.Core.Tests/HelperClasses/EnumPerfProfileElement.cs
Tests/FiftyOne.Pipeline.Core.Tests/HelperClasses/EnumPerfProfileElementBuilder.cs

Add a test and a test element for a configured element that has an Enum type.

FEAT: Add Parsing and Setting for Enum.Types in BuildFromConfiguration

---

FiftyOne.Pipeline.Core/Data/IWeightedValue.cs
FiftyOne.Pipeline.Core/Data/WeightedValue.cs
FiftyOne.Pipeline.Core/Data/WktString.cs
FiftyOne.Pipeline.Core/Utils/TypeNameHelper.cs
Tests/FiftyOne.Pipeline.Core.Tests/Data/WeightedValueTests.cs
Tests/FiftyOne.Pipeline.Core.Tests/Data/WktStringTests.cs
Tests/FiftyOne.Pipeline.Core.Tests/Utils/TypeNameHelperTest.cs
Tests/FiftyOne.Pipeline.Core.Tests/Utils/TypeNameHelperTests.cs

- Add `TypeNameHelper` and tests.
- As a replacement for [MemberInfo.Name](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.name?view=netstandard-2.0#system-reflection-memberinfo-name) (inherited by [Type](https://learn.microsoft.com/en-us/dotnet/api/system.type?view=netstandard-2.0))
- Respects and describes generic parameters, e.g. `IAspectPropertyValue<String>` vs ``IAspectPropertyValue`1``
- Add `WeightedValue` and tests.
- https://github.com/51Degrees/specifications/blob/feature/ip/pipeline-specification/features/weighted-values.md
- https://github.com/51Degrees/specifications/blob/feature/ip/ip-intelligence-specification/data-model.md#property-details
- Add `WktString` and tests.
- https://github.com/51Degrees/specifications/blob/feature/ip/ip-intelligence-sp …

Add new shared types

---

ci/options.json

Motivation: improve stability of the builds, as Debug often freezes.

ci: remove macos Debug build variant from options.json and build Release on macos-latest

---

FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTemplateTests.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTests.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTestsBase.cs

- Move Driver constructor/`Quit` calls to static `ClassInit`/`ClassCleanup` methods.
- https://github.com/51Degrees/pipeline-dotnet/actions/runs/13154247404/job/36707698313#step:5:297
- ✅ https://github.com/postindustria-tech/pipeline-dotnet/actions/runs/13164579306
- https://github.com/51Degrees/pipeline-dotnet/pull/190

Make `ChromeDriver` initialize once per class rather than per test. (on `main`)

---

FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTemplateTests.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTests.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JavaScriptBuilderElementTests/JavaScriptBuilderElementTestsBase.cs

- Move Driver constructor/`Quit` calls to static `ClassInit`/`ClassCleanup` methods.
- https://github.com/51Degrees/pipeline-dotnet/actions/runs/13154247404/job/36707698313#step:5:297
- ✅ https://github.com/postindustria-tech/pipeline-dotnet/actions/runs/13163422918

Make `ChromeDriver` initialize once per class rather than per test. (on `v4.5`)

---

FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JsonBuilderElement/Converters/IPAddressValueConverter.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JsonBuilderElement/Converters/WeightedValueConverter.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JsonBuilderElement/FlowElement/JsonBuilderElement.cs
FiftyOne.Pipeline.Elements/FiftyOne.Pipeline.JsonBuilderElementTests/JsonBuilderElementTests.cs
Web Integration/Tests/FiftyOne.Pipeline.Web.Framework.Tests/app.config

- Add serializers and test cases for `IPAddress` and `IWeightedValue` support in `JsonBuilderElement`.
- Fix binding redirects in `MathExample` test.

Support `IPAddress` and `IWeightedValue` in `JsonBuilderElement`
